name: "AI Agent Evaluation"

on: 
  workflow_call: 
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login using Federated Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Run Evaluation
        uses: microsoft/ai-agent-evals@v2-beta
        with:
          # Replace placeholders with values for your Azure AI Project
          azure-ai-project-endpoint: "https://azure-ai-foundry-swe.services.ai.azure.com/api/projects/firstProject"
          deployment-name: "gpt-4.1"
          agent-ids: >-
            asst_UXLcNSPtytUXZY18tuBJB8NR,
            asst_83PNm4AbaoclOQVtNvT4uBxR
          data-path: ${{ github.workspace }}/data/eval_data.json
          evaluation-result-view: all-scores